apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-qa-api

resources:
  - ../../base

images:
  - name: ghcr.io/your-org/ai-qa-api
    newTag: "0.2.0"

commonLabels:
  environment: prod

patches:
  - target:
      kind: Deployment
      name: ai-qa-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 6
